"""initial schema - all 15 tables

Revision ID: b5cdfe28e774
Revises: 
Create Date: 2026-03-04 14:58:54.420958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5cdfe28e774'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='TIER_CHANGE / SECTOR_DRIFT / STALE_DATA / FM_SIGNAL_UPDATE / HARD_OVERRIDE'),
    sa.Column('severity', sa.String(length=10), nullable=False, comment='INFO / WARNING / CRITICAL'),
    sa.Column('mstar_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_fund', 'alert_events', ['mstar_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_alerts_unread', 'alert_events', ['is_read', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_read IS false'))
    op.create_table('category_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('return_2y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('cumulative_return_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('cumulative_return_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('cumulative_return_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code', 'as_of_date', name='uq_cat_returns_code_date')
    )
    op.create_index('idx_cat_returns_code_date', 'category_returns', ['category_code', sa.literal_column('as_of_date DESC')], unique=False)
    op.create_table('engine_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('fund_crs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('computed_date', sa.Date(), nullable=False),
    sa.Column('qfs', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('fsas', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('qfs_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fsas_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('crs', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False, comment='CORE / QUALITY / WATCH / CAUTION / EXIT'),
    sa.Column('action', sa.String(length=10), nullable=False, comment='BUY / SIP / HOLD_PLUS / HOLD / REDUCE / REVIEW / EXIT'),
    sa.Column('override_applied', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=200), nullable=True),
    sa.Column('original_tier', sa.String(length=10), nullable=True),
    sa.Column('action_rationale', sa.Text(), nullable=True),
    sa.Column('qfs_id', sa.UUID(), nullable=True),
    sa.Column('fsas_id', sa.UUID(), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'computed_date', name='uq_crs_mstar_date')
    )
    op.create_index('idx_crs_mstar_date', 'fund_crs', ['mstar_id', sa.literal_column('computed_date DESC')], unique=False)
    op.create_index('idx_crs_tier', 'fund_crs', ['tier', sa.literal_column('crs DESC')], unique=False)
    op.create_table('fund_fsas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('fm_signal_date', sa.Date(), nullable=False, comment='Which signal version drove this'),
    sa.Column('holdings_date', sa.Date(), nullable=False, comment='Which holdings data was used'),
    sa.Column('raw_fsas', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('fsas', sa.Numeric(precision=8, scale=4), nullable=False, comment='Normalised 0-100'),
    sa.Column('sector_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='{sector: {exposure_pct, signal, signal_weight, contribution}}'),
    sa.Column('stale_holdings_flag', sa.Boolean(), nullable=False, comment='Holdings > 45 days old'),
    sa.Column('sector_drift_alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[{sector, prev_pct, curr_pct, change}]'),
    sa.Column('avoid_exposure_pct', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total exposure to AVOID sectors'),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'fm_signal_date', name='uq_fsas_mstar_signal')
    )
    op.create_index('idx_fsas_mstar_date', 'fund_fsas', ['mstar_id', sa.literal_column('fm_signal_date DESC')], unique=False)
    op.create_table('fund_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False, comment='Morningstar SecId'),
    sa.Column('fund_id', sa.String(length=20), nullable=True, comment='Morningstar FundId (portfolio-level)'),
    sa.Column('amc_id', sa.String(length=20), nullable=True, comment='ProviderCompanyID'),
    sa.Column('legal_name', sa.String(length=300), nullable=False, comment='LegalName'),
    sa.Column('fund_name', sa.String(length=200), nullable=True, comment='FundName (short)'),
    sa.Column('amc_name', sa.String(length=300), nullable=True, comment='ProviderCompanyName'),
    sa.Column('category_name', sa.String(length=200), nullable=False, comment='FundLevelCategoryName (SEBI category)'),
    sa.Column('broad_category', sa.String(length=200), nullable=True, comment='BroadCategoryGroup'),
    sa.Column('inception_date', sa.Date(), nullable=True, comment='InceptionDate'),
    sa.Column('managers', sa.String(length=500), nullable=True, comment='Manager names'),
    sa.Column('manager_education', sa.String(length=500), nullable=True, comment='CollegeEducationDetail'),
    sa.Column('manager_birth_year', sa.Integer(), nullable=True, comment='year_of_birth'),
    sa.Column('manager_certification', sa.String(length=200), nullable=True, comment='certification_name'),
    sa.Column('purchase_mode', sa.Integer(), nullable=False, comment='1=Regular, 2=Direct'),
    sa.Column('is_index_fund', sa.Boolean(), nullable=False, comment='IndexFund'),
    sa.Column('is_fund_of_funds', sa.Boolean(), nullable=False, comment='FundOfFunds'),
    sa.Column('is_insurance_product', sa.Boolean(), nullable=False, comment='AvailableInsuranceProduct'),
    sa.Column('is_etf', sa.Boolean(), nullable=False, comment='ExchangeTradedShare'),
    sa.Column('performance_ready', sa.Boolean(), nullable=False, comment='PerformanceReady'),
    sa.Column('isin', sa.String(length=12), nullable=True, comment='ISIN'),
    sa.Column('amfi_code', sa.String(length=10), nullable=True, comment='AMFICode'),
    sa.Column('sip_available', sa.Boolean(), nullable=False, comment='SIPAvailability'),
    sa.Column('net_expense_ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='InterimNetExpenseRatio'),
    sa.Column('gross_expense_ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='GrossExpenseRatio'),
    sa.Column('turnover_ratio', sa.Numeric(precision=8, scale=4), nullable=True, comment='InterimTurnoverRatio'),
    sa.Column('indian_risk_level', sa.String(length=50), nullable=True, comment='IndianRiskLevel'),
    sa.Column('benchmark_risk_level', sa.String(length=50), nullable=True, comment='india_benchmark_risk_level'),
    sa.Column('fund_risk_level', sa.String(length=50), nullable=True, comment='india_fund_risk_level'),
    sa.Column('primary_benchmark', sa.String(length=300), nullable=True, comment='PrimaryProspectusBenchmarks'),
    sa.Column('investment_strategy', sa.Text(), nullable=True, comment='InvestmentStrategy'),
    sa.Column('investment_philosophy', sa.Text(), nullable=True, comment='InvestmentPhilosophy'),
    sa.Column('previous_fund_name', sa.String(length=300), nullable=True, comment='PreviousFundName'),
    sa.Column('previous_name_end_date', sa.Date(), nullable=True, comment='PreviousFundNameEndDate'),
    sa.Column('pricing_frequency', sa.String(length=20), nullable=True, comment='PricingFrequency'),
    sa.Column('legal_structure', sa.String(length=100), nullable=True, comment='LegalStructure'),
    sa.Column('domicile_id', sa.String(length=20), nullable=True, comment='DomicileId'),
    sa.Column('exchange_id', sa.String(length=20), nullable=True, comment='ExchangeId'),
    sa.Column('closed_to_investors', sa.Date(), nullable=True, comment='ClosedToInvestors'),
    sa.Column('lock_in_period', sa.Numeric(precision=10, scale=2), nullable=True, comment='InitialLockupPeriod in years'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Not wound up or merged'),
    sa.Column('is_eligible', sa.Boolean(), nullable=False, comment='Passes universe filter'),
    sa.Column('eligibility_reason', sa.String(length=200), nullable=True, comment='Why ineligible'),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id')
    )
    op.create_index('idx_fund_master_amfi', 'fund_master', ['amfi_code'], unique=False, postgresql_where=sa.text('amfi_code IS NOT NULL'))
    op.create_index('idx_fund_master_category', 'fund_master', ['category_name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_fund_master_eligible', 'fund_master', ['is_eligible', 'category_name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_fund_master_isin', 'fund_master', ['isin'], unique=False, postgresql_where=sa.text('isin IS NOT NULL'))
    op.create_index('idx_fund_master_purchase_mode', 'fund_master', ['purchase_mode', 'category_name'], unique=False)
    op.create_table('fund_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=19, scale=5), nullable=True),
    sa.Column('nav_change', sa.Numeric(precision=19, scale=5), nullable=True),
    sa.Column('return_1d', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_1w', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_1m', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_3m', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_6m', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_ytd', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_2y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_4y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_7y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('return_since_inception', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('cumulative_return_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('cumulative_return_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('cumulative_return_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('nav_52w_high', sa.Numeric(precision=19, scale=5), nullable=True),
    sa.Column('nav_52w_high_date', sa.Date(), nullable=True),
    sa.Column('nav_52w_low', sa.Numeric(precision=19, scale=5), nullable=True),
    sa.Column('nav_52w_low_date', sa.Date(), nullable=True),
    sa.Column('calendar_year_returns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'nav_date', name='uq_fund_perf_mstar_date')
    )
    op.create_index('idx_fund_perf_date', 'fund_performance', [sa.literal_column('nav_date DESC')], unique=False)
    op.create_index('idx_fund_perf_mstar_date', 'fund_performance', ['mstar_id', sa.literal_column('nav_date DESC')], unique=False)
    op.create_table('fund_qfs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('computed_date', sa.Date(), nullable=False),
    sa.Column('score_1y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score_5y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score_10y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wfs_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('qfs', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('data_completeness_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='% of 52 possible data points available'),
    sa.Column('missing_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of null metrics + how handled'),
    sa.Column('available_horizons', sa.Integer(), nullable=False, comment='Count of horizons with data'),
    sa.Column('metric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{metric: {horizon: {raw, normalised, rank}}}'),
    sa.Column('quartile_consistency', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{1y: Q1, 3y: Q1, 5y: Q2, 10y: Q1}'),
    sa.Column('cross_validation_flag', sa.String(length=50), nullable=True, comment='CONSISTENT / REVIEW_NEEDED / DATA_GAP'),
    sa.Column('data_vintage', sa.Date(), nullable=True, comment='Date of input data used'),
    sa.Column('input_hash', sa.String(length=64), nullable=True, comment='SHA-256 of input data'),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('category_universe_size', sa.Integer(), nullable=True, comment='Funds in category at compute time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'computed_date', name='uq_qfs_mstar_date')
    )
    op.create_index('idx_qfs_mstar_date', 'fund_qfs', ['mstar_id', sa.literal_column('computed_date DESC')], unique=False)
    op.create_table('fund_ranks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('month_end_date', sa.Date(), nullable=False),
    sa.Column('rank_1m_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_3m_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_6m_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_1y_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_2y_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_3y_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_5y_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_7y_quartile', sa.Integer(), nullable=True),
    sa.Column('rank_10y_quartile', sa.Integer(), nullable=True),
    sa.Column('abs_rank_1m', sa.Integer(), nullable=True),
    sa.Column('abs_rank_3m', sa.Integer(), nullable=True),
    sa.Column('abs_rank_6m', sa.Integer(), nullable=True),
    sa.Column('abs_rank_1y', sa.Integer(), nullable=True),
    sa.Column('abs_rank_2y', sa.Integer(), nullable=True),
    sa.Column('abs_rank_3y', sa.Integer(), nullable=True),
    sa.Column('abs_rank_5y', sa.Integer(), nullable=True),
    sa.Column('abs_rank_7y', sa.Integer(), nullable=True),
    sa.Column('abs_rank_10y', sa.Integer(), nullable=True),
    sa.Column('rank_yr1', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr4', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr5', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr6', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr7', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr8', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr9', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rank_yr10', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'month_end_date', name='uq_ranks_mstar_date')
    )
    op.create_index('idx_ranks_mstar_date', 'fund_ranks', ['mstar_id', sa.literal_column('month_end_date DESC')], unique=False)
    op.create_table('fund_risk_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('month_end_date', sa.Date(), nullable=False),
    sa.Column('sharpe_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('sharpe_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('sharpe_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('alpha_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('alpha_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('alpha_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('beta_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('beta_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('beta_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('std_dev_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('std_dev_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('std_dev_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('sortino_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('sortino_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('sortino_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('treynor_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('treynor_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('treynor_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('treynor_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('tracking_error_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('tracking_error_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('tracking_error_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('tracking_error_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('info_ratio_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('info_ratio_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('info_ratio_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('info_ratio_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_up_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_up_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_up_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_up_10y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_down_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_down_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('capture_down_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('max_drawdown_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('max_drawdown_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('max_drawdown_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('correlation_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('correlation_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('correlation_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('r_squared_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('r_squared_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('r_squared_5y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('skewness_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('skewness_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('kurtosis_1y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('kurtosis_3y', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'month_end_date', name='uq_risk_stats_mstar_date')
    )
    op.create_index('idx_risk_stats_mstar_date', 'fund_risk_stats', ['mstar_id', sa.literal_column('month_end_date DESC')], unique=False)
    op.create_table('fund_sector_exposure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('month_end_date', sa.Date(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False, comment='Same taxonomy as sector_signals'),
    sa.Column('exposure_pct', sa.Numeric(precision=8, scale=4), nullable=False, comment='Percentage allocation 0-100'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='cams / kfintech / morningstar'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mstar_id', 'month_end_date', 'sector_name', name='uq_exposure_fund_date_sector')
    )
    op.create_index('idx_exposure_fund_date', 'fund_sector_exposure', ['mstar_id', sa.literal_column('month_end_date DESC')], unique=False)
    op.create_table('ingestion_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_name', sa.String(length=50), nullable=False, comment='JHV_MASTER / JHV_PERFORMANCE_DAILY / JHV_RISK_MONTHLY / JHV_CALENDAR_ANNUAL / CAMS_HOLDINGS'),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('records_total', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='SUCCESS / PARTIAL / FAILED'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mstar_id', sa.String(length=20), nullable=False),
    sa.Column('computation_type', sa.String(length=10), nullable=False, comment='QFS / FSAS / CRS'),
    sa.Column('old_value', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('old_tier', sa.String(length=10), nullable=True),
    sa.Column('new_tier', sa.String(length=10), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=True, comment='monthly_recompute / fm_signal_update / manual_override'),
    sa.Column('computed_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('nse_symbol', sa.String(length=20), nullable=True),
    sa.Column('bse_code', sa.String(length=10), nullable=True),
    sa.Column('sector_name', sa.String(length=100), nullable=False, comment='Maps to FM signal taxonomy'),
    sa.Column('sub_sector', sa.String(length=100), nullable=True, comment='For future v2 sub-sector support'),
    sa.Column('nifty_index', sa.String(length=200), nullable=True, comment='Aligned Nifty/BSE index'),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index('idx_sector_mapping_sector', 'sector_mapping', ['sector_name'], unique=False)
    op.create_table('sector_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False, comment='FM sector taxonomy name'),
    sa.Column('signal', sa.String(length=20), nullable=False, comment='OVERWEIGHT / ACCUMULATE / NEUTRAL / UNDERWEIGHT / AVOID'),
    sa.Column('confidence', sa.String(length=10), nullable=False, comment='HIGH / MEDIUM / LOW'),
    sa.Column('signal_weight', sa.Numeric(precision=5, scale=2), nullable=False, comment='Numeric weight derived from signal'),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False, comment='FM name'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='FALSE when superseded by newer signal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_active', 'sector_signals', ['is_active', 'sector_name'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('idx_signals_date', 'sector_signals', [sa.literal_column('effective_date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signals_date', table_name='sector_signals')
    op.drop_index('idx_signals_active', table_name='sector_signals', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('sector_signals')
    op.drop_index('idx_sector_mapping_sector', table_name='sector_mapping')
    op.drop_table('sector_mapping')
    op.drop_table('score_audit_log')
    op.drop_table('ingestion_log')
    op.drop_index('idx_exposure_fund_date', table_name='fund_sector_exposure')
    op.drop_table('fund_sector_exposure')
    op.drop_index('idx_risk_stats_mstar_date', table_name='fund_risk_stats')
    op.drop_table('fund_risk_stats')
    op.drop_index('idx_ranks_mstar_date', table_name='fund_ranks')
    op.drop_table('fund_ranks')
    op.drop_index('idx_qfs_mstar_date', table_name='fund_qfs')
    op.drop_table('fund_qfs')
    op.drop_index('idx_fund_perf_mstar_date', table_name='fund_performance')
    op.drop_index('idx_fund_perf_date', table_name='fund_performance')
    op.drop_table('fund_performance')
    op.drop_index('idx_fund_master_purchase_mode', table_name='fund_master')
    op.drop_index('idx_fund_master_isin', table_name='fund_master', postgresql_where=sa.text('isin IS NOT NULL'))
    op.drop_index('idx_fund_master_eligible', table_name='fund_master', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_fund_master_category', table_name='fund_master', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_fund_master_amfi', table_name='fund_master', postgresql_where=sa.text('amfi_code IS NOT NULL'))
    op.drop_table('fund_master')
    op.drop_index('idx_fsas_mstar_date', table_name='fund_fsas')
    op.drop_table('fund_fsas')
    op.drop_index('idx_crs_tier', table_name='fund_crs')
    op.drop_index('idx_crs_mstar_date', table_name='fund_crs')
    op.drop_table('fund_crs')
    op.drop_table('engine_config')
    op.drop_index('idx_cat_returns_code_date', table_name='category_returns')
    op.drop_table('category_returns')
    op.drop_index('idx_alerts_unread', table_name='alert_events', postgresql_where=sa.text('is_read IS false'))
    op.drop_index('idx_alerts_fund', table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
