"""
models/db/alert_events.py

Alert events generated by the scoring engine — tier changes, sector drift,
stale data warnings, FM signal updates, hard overrides.
"""

from __future__ import annotations
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, Index, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class AlertEvent(Base):
    __tablename__ = "alert_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    alert_type: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="TIER_CHANGE / SECTOR_DRIFT / STALE_DATA / FM_SIGNAL_UPDATE / HARD_OVERRIDE"
    )
    severity: Mapped[str] = mapped_column(
        String(10), nullable=False, default="INFO",
        comment="INFO / WARNING / CRITICAL"
    )
    mstar_id: Mapped[Optional[str]] = mapped_column(String(20))
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    details: Mapped[Optional[dict]] = mapped_column(JSONB)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    __table_args__ = (
        Index("idx_alerts_unread", "is_read", created_at.desc(),
              postgresql_where=is_read.is_(False)),
        Index("idx_alerts_fund", "mstar_id", created_at.desc()),
    )
